# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class ClassificationResult(BaseModel):
    is_clinical_transcript: typing.Optional[bool] = Field(default=None, description='True only if the text is a real veterinary clinical consultation transcript')
    reason: typing.Optional[str] = Field(default=None, description='One sentence explaining the classification')

class DiagnosticEvent(BaseModel):
    type: typing.Optional[typing_extensions.Literal['diagnostic']] = None
    order: typing.Optional[int] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    test_name: typing.Optional[str] = None
    indication: typing.Optional[str] = None
    decision: typing.Optional[types.DecisionStatus] = None
    result: typing.Optional[str] = None

class HistoryEvent(BaseModel):
    type: typing.Optional[typing_extensions.Literal['history']] = None
    order: typing.Optional[int] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None

class PhysicalExamEvent(BaseModel):
    type: typing.Optional[typing_extensions.Literal['physical_exam']] = None
    order: typing.Optional[int] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    findings_by_system: typing.Optional[str] = Field(default=None, description='Body system findings as a comma-separated or free-text string')

class RecommendationEvent(BaseModel):
    type: typing.Optional[typing_extensions.Literal['recommendation']] = None
    order: typing.Optional[int] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    category: typing.Optional[types.RecommendationCategory] = None
    specifics: typing.Optional[str] = None

class Timeline(BaseModel):
    events: typing.List[typing.Union["HistoryEvent", "PhysicalExamEvent", "VitalsEvent", "DiagnosticEvent", "TreatmentEvent", "RecommendationEvent"]]

class TreatmentEvent(BaseModel):
    type: typing.Optional[typing_extensions.Literal['treatment']] = None
    order: typing.Optional[int] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    name: typing.Optional[str] = Field(default=None, description='Treatment or medication name')
    dose: typing.Optional[str] = None
    route: typing.Optional[str] = None
    decision: typing.Optional[types.DecisionStatus] = None
    progress: typing.Optional[types.ProgressStatus] = None

class VitalsEvent(BaseModel):
    type: typing.Optional[typing_extensions.Literal['vitals']] = None
    order: typing.Optional[int] = None
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    temperature_f: typing.Optional[float] = None
    heart_rate_bpm: typing.Optional[int] = None
    respiratory_rate: typing.Optional[int] = None
    weight_kg: typing.Optional[float] = None
    mucous_membranes: typing.Optional[str] = None
    capillary_refill_seconds: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
