# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DiagnosticEvent": types.DiagnosticEvent,
    "stream_types.DiagnosticEvent": stream_types.DiagnosticEvent,

    "types.HistoryEvent": types.HistoryEvent,
    "stream_types.HistoryEvent": stream_types.HistoryEvent,

    "types.PhysicalExamEvent": types.PhysicalExamEvent,
    "stream_types.PhysicalExamEvent": stream_types.PhysicalExamEvent,

    "types.RecommendationEvent": types.RecommendationEvent,
    "stream_types.RecommendationEvent": stream_types.RecommendationEvent,

    "types.Timeline": types.Timeline,
    "stream_types.Timeline": stream_types.Timeline,

    "types.TreatmentEvent": types.TreatmentEvent,
    "stream_types.TreatmentEvent": stream_types.TreatmentEvent,

    "types.VitalsEvent": types.VitalsEvent,
    "stream_types.VitalsEvent": stream_types.VitalsEvent,


    "types.DecisionStatus": types.DecisionStatus,

    "types.ProgressStatus": types.ProgressStatus,

    "types.RecommendationCategory": types.RecommendationCategory,

}