# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class DecisionStatus(str, Enum):
    Approved = "Approved"
    Declined = "Declined"
    Pending = "Pending"

class ProgressStatus(str, Enum):
    Completed = "Completed"
    InProgress = "InProgress"
    Pending = "Pending"

class RecommendationCategory(str, Enum):
    Vaccine = "Vaccine"
    Medication = "Medication"
    Diet = "Diet"
    FollowUp = "FollowUp"
    Other = "Other"

# #########################################################################
# Generated classes (8)
# #########################################################################

class ClassificationResult(BaseModel):
    is_clinical_transcript: bool = Field(description='True only if the text is a real veterinary clinical consultation transcript')
    reason: str = Field(description='One sentence explaining the classification')

class DiagnosticEvent(BaseModel):
    type: typing_extensions.Literal['diagnostic']
    order: int
    title: str
    description: str
    test_name: str
    indication: typing.Optional[str] = None
    decision: DecisionStatus
    result: typing.Optional[str] = None

class HistoryEvent(BaseModel):
    type: typing_extensions.Literal['history']
    order: int
    title: str
    description: str

class PhysicalExamEvent(BaseModel):
    type: typing_extensions.Literal['physical_exam']
    order: int
    title: str
    description: str
    findings_by_system: typing.Optional[str] = Field(default=None, description='Body system findings as a comma-separated or free-text string')

class RecommendationEvent(BaseModel):
    type: typing_extensions.Literal['recommendation']
    order: int
    title: str
    description: str
    category: RecommendationCategory
    specifics: typing.Optional[str] = None

class Timeline(BaseModel):
    events: typing.List[typing.Union["HistoryEvent", "PhysicalExamEvent", "VitalsEvent", "DiagnosticEvent", "TreatmentEvent", "RecommendationEvent"]]

class TreatmentEvent(BaseModel):
    type: typing_extensions.Literal['treatment']
    order: int
    title: str
    description: str
    name: str = Field(description='Treatment or medication name')
    dose: typing.Optional[str] = None
    route: typing.Optional[str] = None
    decision: DecisionStatus
    progress: typing.Optional[ProgressStatus] = None

class VitalsEvent(BaseModel):
    type: typing_extensions.Literal['vitals']
    order: int
    title: str
    description: str
    temperature_f: typing.Optional[float] = None
    heart_rate_bpm: typing.Optional[int] = None
    respiratory_rate: typing.Optional[int] = None
    weight_kg: typing.Optional[float] = None
    mucous_membranes: typing.Optional[str] = None
    capillary_refill_seconds: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
