from pydantic import BaseModel, Field

from baml_client.types import Timeline as BamlTimeline


class ExtractRequest(BaseModel):
    transcript: str = Field(..., description="Plain-text consultation transcript")


# Response is the BAML Timeline directly. The discriminated-union event types
# generated by BAML are Pydantic v2 models, so FastAPI serializes them natively.
ExtractResponse = BamlTimeline


class ErrorBody(BaseModel):
    error: str
    detail: str | None = None
